[2023-12-14T02:05:51.911+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2023-12-13T00:00:00+00:00 [queued]>
[2023-12-14T02:05:51.947+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2023-12-13T00:00:00+00:00 [queued]>
[2023-12-14T02:05:51.948+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-14T02:05:51.971+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): inaccurate> on 2023-12-13 00:00:00+00:00
[2023-12-14T02:05:51.979+0000] {standard_task_runner.py:57} INFO - Started process 337 to run task
[2023-12-14T02:05:51.984+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2023-12-13T00:00:00+00:00', '--job-id', '329', '--raw', '--subdir', 'DAGS_FOLDER/my_dog.py', '--cfg-path', '/tmp/tmpjskxunk2']
[2023-12-14T02:05:51.987+0000] {standard_task_runner.py:85} INFO - Job 329: Subtask inaccurate
[2023-12-14T02:05:52.058+0000] {task_command.py:416} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2023-12-13T00:00:00+00:00 [running]> on host cbe761bfd41f
[2023-12-14T02:05:52.176+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2023-12-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-13T00:00:00+00:00'
[2023-12-14T02:05:52.179+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-14T02:05:52.180+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2023-12-14T02:05:52.195+0000] {subprocess.py:86} INFO - Output:
[2023-12-14T02:05:52.198+0000] {subprocess.py:93} INFO - inaccurate
[2023-12-14T02:05:52.200+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-14T02:05:52.234+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20231213T000000, start_date=20231214T020551, end_date=20231214T020552
[2023-12-14T02:05:52.278+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-14T02:05:52.308+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
