[2023-12-19T09:31:33.375+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: service_oriented_class_project.insert_traffic manual__2023-12-19T09:31:21.325737+00:00 [queued]>
[2023-12-19T09:31:33.387+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: service_oriented_class_project.insert_traffic manual__2023-12-19T09:31:21.325737+00:00 [queued]>
[2023-12-19T09:31:33.387+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-19T09:31:33.403+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_traffic> on 2023-12-19 09:31:21.325737+00:00
[2023-12-19T09:31:33.413+0000] {standard_task_runner.py:57} INFO - Started process 6161 to run task
[2023-12-19T09:31:33.417+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'service_oriented_class_project', 'insert_traffic', 'manual__2023-12-19T09:31:21.325737+00:00', '--job-id', '418', '--raw', '--subdir', 'DAGS_FOLDER/service_oriented_class_project.py', '--cfg-path', '/tmp/tmppkocrygn']
[2023-12-19T09:31:33.420+0000] {standard_task_runner.py:85} INFO - Job 418: Subtask insert_traffic
[2023-12-19T09:31:33.465+0000] {task_command.py:416} INFO - Running <TaskInstance: service_oriented_class_project.insert_traffic manual__2023-12-19T09:31:21.325737+00:00 [running]> on host f97daee24bd9
[2023-12-19T09:31:33.530+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='christinelee1114@gmail.com' AIRFLOW_CTX_DAG_OWNER='xin' AIRFLOW_CTX_DAG_ID='service_oriented_class_project' AIRFLOW_CTX_TASK_ID='insert_traffic' AIRFLOW_CTX_EXECUTION_DATE='2023-12-19T09:31:21.325737+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-19T09:31:21.325737+00:00'
[2023-12-19T09:31:33.532+0000] {sql.py:274} INFO - Executing: 
            COPY traffic(年,月,日,日期,受傷人數,市區鄉鎮,是否飲酒,時間,死亡人數,當事者順位,白天or夜晚,經度,緯度,縣市,道路類型)
            FROM 'D:/Airflow-docker/dags/data/traffic_ETL.csv' DELIMITER ',' CSV HEADER;
            
[2023-12-19T09:31:33.540+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-19T09:31:33.548+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-19T09:31:33.599+0000] {sql.py:418} INFO - Running statement: 
            COPY traffic(年,月,日,日期,受傷人數,市區鄉鎮,是否飲酒,時間,死亡人數,當事者順位,白天or夜晚,經度,緯度,縣市,道路類型)
            FROM 'D:/Airflow-docker/dags/data/traffic_ETL.csv' DELIMITER ',' CSV HEADER;
            , parameters: None
[2023-12-19T09:31:33.604+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "traffic" does not exist

[2023-12-19T09:31:33.613+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=service_oriented_class_project, task_id=insert_traffic, execution_date=20231219T093121, start_date=20231219T093133, end_date=20231219T093133
[2023-12-19T09:31:33.625+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 418 for task insert_traffic (relation "traffic" does not exist
; 6161)
[2023-12-19T09:31:33.670+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-19T09:31:33.686+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
