[2023-12-07T12:57:18.516+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2023-12-07T12:57:11.881249+00:00 [queued]>
[2023-12-07T12:57:18.525+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2023-12-07T12:57:11.881249+00:00 [queued]>
[2023-12-07T12:57:18.526+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-07T12:57:18.536+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): inaccurate> on 2023-12-07 12:57:11.881249+00:00
[2023-12-07T12:57:18.544+0000] {standard_task_runner.py:57} INFO - Started process 38284 to run task
[2023-12-07T12:57:18.547+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2023-12-07T12:57:11.881249+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/my_dog1.py', '--cfg-path', '/tmp/tmpxidtmvjk']
[2023-12-07T12:57:18.548+0000] {standard_task_runner.py:85} INFO - Job 56: Subtask inaccurate
[2023-12-07T12:57:18.589+0000] {task_command.py:416} INFO - Running <TaskInstance: my_dag.inaccurate manual__2023-12-07T12:57:11.881249+00:00 [running]> on host 7fd8dd875aa1
[2023-12-07T12:57:18.647+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2023-12-07T12:57:11.881249+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-07T12:57:11.881249+00:00'
[2023-12-07T12:57:18.650+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-07T12:57:18.651+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2023-12-07T12:57:18.662+0000] {subprocess.py:86} INFO - Output:
[2023-12-07T12:57:18.663+0000] {subprocess.py:93} INFO - inaccurate
[2023-12-07T12:57:18.664+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-07T12:57:18.684+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20231207T125711, start_date=20231207T125718, end_date=20231207T125718
[2023-12-07T12:57:18.720+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-07T12:57:18.732+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
