[2023-12-19T05:19:21.874+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: steal_etl_storeToPostgres.steal_ETL manual__2023-12-19T05:19:20.087054+00:00 [queued]>
[2023-12-19T05:19:21.882+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: steal_etl_storeToPostgres.steal_ETL manual__2023-12-19T05:19:20.087054+00:00 [queued]>
[2023-12-19T05:19:21.883+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-19T05:19:21.894+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): steal_ETL> on 2023-12-19 05:19:20.087054+00:00
[2023-12-19T05:19:21.902+0000] {standard_task_runner.py:57} INFO - Started process 2245 to run task
[2023-12-19T05:19:21.904+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'steal_etl_storeToPostgres', 'steal_ETL', 'manual__2023-12-19T05:19:20.087054+00:00', '--job-id', '395', '--raw', '--subdir', 'DAGS_FOLDER/steal_etl_storeToPostgres.py', '--cfg-path', '/tmp/tmpmhdbgulr']
[2023-12-19T05:19:21.907+0000] {standard_task_runner.py:85} INFO - Job 395: Subtask steal_ETL
[2023-12-19T05:19:21.946+0000] {task_command.py:416} INFO - Running <TaskInstance: steal_etl_storeToPostgres.steal_ETL manual__2023-12-19T05:19:20.087054+00:00 [running]> on host f97daee24bd9
[2023-12-19T05:19:22.188+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='christinelee1114@gmail.com' AIRFLOW_CTX_DAG_OWNER='xin' AIRFLOW_CTX_DAG_ID='steal_etl_storeToPostgres' AIRFLOW_CTX_TASK_ID='steal_ETL' AIRFLOW_CTX_EXECUTION_DATE='2023-12-19T05:19:20.087054+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-19T05:19:20.087054+00:00'
[2023-12-19T05:19:22.221+0000] {warnings.py:109} WARNING - /opt/***/dags/steal_etl_storeToPostgres.py:55: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_loc.drop('_id', axis=1, inplace=True)

[2023-12-19T05:19:22.222+0000] {warnings.py:109} WARNING - /opt/***/dags/steal_etl_storeToPostgres.py:56: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_loc.rename(columns=newcolumns, inplace=True)

[2023-12-19T05:19:22.227+0000] {warnings.py:109} WARNING - /opt/***/dags/steal_etl_storeToPostgres.py:59: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_loc['日期'] = (df_loc['年'] + 1911).astype(str) + df_loc['月'].astype(str).str.zfill(2) + df_loc['日'].astype(str).str.zfill(2)

[2023-12-19T05:19:22.243+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-19T05:19:22.256+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=steal_etl_storeToPostgres, task_id=steal_ETL, execution_date=20231219T051920, start_date=20231219T051921, end_date=20231219T051922
[2023-12-19T05:19:22.319+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-19T05:19:22.495+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
