[2023-12-12T15:22:12.281+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_and_store_to_mysql_04.insert_sql scheduled__2023-12-11T15:21:52.129828+00:00 [queued]>
[2023-12-12T15:22:12.288+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_and_store_to_mysql_04.insert_sql scheduled__2023-12-11T15:21:52.129828+00:00 [queued]>
[2023-12-12T15:22:12.288+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-12T15:22:12.299+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_sql> on 2023-12-11 15:21:52.129828+00:00
[2023-12-12T15:22:12.307+0000] {standard_task_runner.py:57} INFO - Started process 5203 to run task
[2023-12-12T15:22:12.310+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crawl_and_store_to_mysql_04', 'insert_sql', 'scheduled__2023-12-11T15:21:52.129828+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/crawl_and_store_to_mysql_04.py', '--cfg-path', '/tmp/tmpowda3kyn']
[2023-12-12T15:22:12.313+0000] {standard_task_runner.py:85} INFO - Job 102: Subtask insert_sql
[2023-12-12T15:22:12.348+0000] {task_command.py:416} INFO - Running <TaskInstance: crawl_and_store_to_mysql_04.insert_sql scheduled__2023-12-11T15:21:52.129828+00:00 [running]> on host 7fd8dd875aa1
[2023-12-12T15:22:12.399+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='xin' AIRFLOW_CTX_DAG_ID='crawl_and_store_to_mysql_04' AIRFLOW_CTX_TASK_ID='insert_sql' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T15:21:52.129828+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T15:21:52.129828+00:00'
[2023-12-12T15:22:12.402+0000] {sql.py:274} INFO - Executing: 
            COPY cctv_data(location, area, longitude, latitude)
            FROM '/data/CCTV.csv' DELIMITER ',' CSV HEADER;
            
[2023-12-12T15:22:12.409+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-12T15:22:12.417+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-12T15:22:12.470+0000] {sql.py:418} INFO - Running statement: 
            COPY cctv_data(location, area, longitude, latitude)
            FROM '/data/CCTV.csv' DELIMITER ',' CSV HEADER;
            , parameters: None
[2023-12-12T15:22:12.474+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/data/CCTV.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2023-12-12T15:22:12.483+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crawl_and_store_to_mysql_04, task_id=insert_sql, execution_date=20231211T152152, start_date=20231212T152212, end_date=20231212T152212
[2023-12-12T15:22:12.496+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 102 for task insert_sql (could not open file "/data/CCTV.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 5203)
[2023-12-12T15:22:12.523+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-12T15:22:12.540+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
